. .bashrc

export HAOKU_READ=release
export PYTHONPATH=$PYTHONPATH:~/checkouts/haoku.net/read:~/checkouts/simin
export EDITOR=vim

. bin/activate

cd ~/checkouts/haoku.net

alias chk='cd ~/checkouts/haoku.net'

alias web-test-start='HAOKU_TEST=TEST ~/bin/uwsgi ~/etc/web.test.xml'
alias web-test-reload='HAOKU_TEST=TEST ~/bin/uwsgi --reload ~/run/web.test.pid'
alias web-test-stop='HAOKU_TEST=TEST ~/bin/uwsgi --stop ~/run/web.test.pid'

alias api-v1-test-start='HAOKU_TEST=TEST ~/bin/uwsgi ~/etc/api.v1.test.xml'
alias api-v1-test-reload='HAOKU_TEST=TEST ~/bin/uwsgi --reload ~/run/api.v1.test.pid'
alias api-v1-test-stop='HAOKU_TEST=TEST ~/bin/uwsgi --stop ~/run/api.v1.test.pid'

alias accounts-test-start='HAOKU_TEST=TEST ~/bin/uwsgi ~/etc/accounts.test.xml'
alias accounts-test-reload='HAOKU_TEST=TEST ~/bin/uwsgi --reload ~/run/accounts.test.pid'
alias accounts-test-stop='HAOKU_TEST=TEST ~/bin/uwsgi --stop ~/run/accounts.test.pid'

alias accounts-api-v1-test-start='HAOKU_TEST=TEST ~/bin/uwsgi ~/etc/accounts.api.v1.test.xml'
alias accounts-api-v1-test-reload='HAOKU_TEST=TEST ~/bin/uwsgi --reload ~/run/accounts.api.v1.test.pid'
alias accounts-api-v1-test-stop='HAOKU_TEST=TEST ~/bin/uwsgi --stop ~/run/accounts.api.v1.test.pid'
